print('Welcome to the Diploma Marks and Percentage Calculator for AP Diploma Students for C20 Circullam.')
f=input('Your Name:')
g=input('Your PIN Number:')
a=float(input('First Year Marks:'))
b=float(input('Third Semester Marks:'))
c=float(input('Fourth Semester Marks:'))
d=float(input('Fifth Semester Marks:'))
e=float(input('Industrial Training Marks:'))
print(f+' '+'Bearing PIN Number'+' '+g+'. '+'You Have Secured '+str((a*0.25)+b+c+d+e)+' '+'Marks '+'and'+' '+str((((a*0.25)+b+c+d+e)/(3750))*100)+' '+'Percentage')
print('This Calculator Has Been Developed By MURI VENKATESWARA KARTHIK')