print('Welcome to the Diploma Marks and Percentage Calculator for AP Diploma Students for C20 Circullam.')
print(' ')
f=input('Your Name: ')
g=input('Your PIN Number: ')
a=float(input('First Year Marks: '))
b=float(input('Third Semester Marks: '))
c=float(input('Fourth Semester Marks: '))
d=float(input('Fifth Semester Marks: '))
e=float(input('Industrial Training Marks: '))
print(' ')
print(f+' '+'Bearing PIN Number'+' '+g+' '+'Has Secured '+str((a*0.25)+b+c+d+e)+' '+'Marks '+'and'+' '+str((((a*0.25)+b+c+d+e)/(3750))*100)+' '+'Percentage')
print(' ')
if input('Do you want to Calculate CGPA for the above result. (Yes/No): ')=='Yes':
    print(' ')
    print('Your CGPA is'+' '+str(((((a*0.25)+b+c+d+e)/(3750))*100)/9.5))
else:
    print(' ')
    print('Thank You for confirmation')
print(' ')
print('Thank You for using our Calculator.')
print(' ')
print('This Calculator Has Been Developed By MURI VENKATESWARA KARTHIK')
